# Generated by Django 5.2b1 on 2025-02-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
    ]
