# Generated by Django 5.2b1 on 2025-02-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ingredients", models.TextField()),
                ("instructions", models.TextField()),
                ("prep_time", models.PositiveIntegerField()),
                ("cook_time", models.PositiveIntegerField()),
                ("servings", models.PositiveIntegerField()),
            ],
        ),
    ]
